name: Codecov
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements/dev-requirements-cython-ciso.txt
      - name: Build Cython extension
        run: python setup.py build_ext --inplace
      - name: Start ClickHouse
        run: make docker-clickhouse
      - name: Run tests
        run: pytest tests.py --cov aiochclient --cov-report=xml -vv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
